Added missing @asyncio.coroutine
Python 3.5 introduces the couple of keywords async/await.

They are compatible with the "yield from" syntax and generator coroutines as
long as they are decorated with @asyncio.coroutine. Some of them where missing,
so code like:

    async def coro(redis_client):
        await redis_client.watch(key)

failed with the error:

    TypeError: object generator can't be used in 'await' expression